sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
addons:
  postgresql: '9.3'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO_VERSION=">=1.7,<1.8"
    - DJANGO_VERSION=">=1.8,<9"
# command to install dependencies
install:
  - pip install Django$DJANGO_VERSION flake8 coverage
  - pip install -e .[all]
# command to run tests
before_script:
  - psql -c 'CREATE DATABASE lazysignup;' -U postgres
script:
  - flake8 .
  - coverage run manage.py test --settings=lazysignup.tests.settings
  - coverage report --fail-under=100
  - psql -c 'DROP DATABASE IF EXISTS test_lazysignup;' -U postgres
  - coverage erase
  - coverage run manage.py test --settings=custom_user_tests.settings
  - coverage report --fail-under=98
branches:
  except:
    - 33-late-logins
